version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "rust-control"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-sugl37e7kyyt"
s3_prefix = "rust-control"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
